# -*- coding: utf-8 -*-
# Copyright 2020 Bumiswa

from . import account_aged_partner
from . import account_cash_flow_report
from . import account_consolidated_journal
from . import account_financial_html_report_line
from . import account_general_ledger
from . import account_generic_tax_report
from . import account_journal
from . import account_move
from . import account_partner_ledger
from . import account_payment
from . import account_reports
from . import account_trail_balance_report
from . import crm_team
from . import pos_config
from . import pos_order
from . import pos_payment_method
from . import pos_session
from . import product_pricelist
from . import product_pricelist_item
from . import product_supplierinfo
from . import product_template
from . import purchase_order
from . import purchase_order_line
from . import purchase_report
from . import report_pos_order
from . import res_users
from . import res_branch
from . import sale_advance_payment_inv
from . import sale_order
from . import sale_order_line
from . import sale_report
from . import stock_inventory
from . import stock_location
from . import stock_move
from . import stock_quant
from . import stock_valuation_layer
from . import stock_warehouse
from . import hr_employee
from . import hr_department
from . import product_replenish_request
from . import res_config_settings
from . import res_company
from . import res_partner
from . import stock_picking
