# License AGPL-3.0 or later (https://www.gnu.org/licenses/agpl).
from . import pos_transaction_code
from . import pos_order_upload
from . import res_division_file
from . import product_items_file
from . import price_change_file
from . import product_barcode_file
from . import product_category_file
from . import product_subcategory_file
from . import res_department_file
from . import group_price_change_file
from . import mix_and_match_combination_file
from . import mix_and_match_partial_file
from . import inherit_account_tax
from . import inherit_uom_uom
from . import inherit_product_categ
from . import inherit_product_sub_categ
from . import inherit_product_template
from . import inherit_res_division
from . import inherit_res_department
from . import inherit_res_group
from . import inherit_pos_payment_method
from . import inherit_pos_config
