# Copyright 2020 Tecnativa - Carlos Dauden
# Copyright 2020 Tecnativa - Sergio Teruel
# License AGPL-3.0 or later (https://www.gnu.org/licenses/agpl).
{
    "name": "Upload Transaction POS",
    "summary": "Upload Transaction POS",
    "version": "16.0.1.0.0",
    "development_status": "Beta",
    "category": "sales",
    "website": False,
    "author": "Dev, WEHA",
    "license": "AGPL-3",
    "application": False,
    "installable": True,
    "depends": ["base", "point_of_sale", "product", "multi_branch_base"],
    "data": [
        "security/contract_security.xml",
        "security/ir.model.access.csv",
        "data/ir_cron.xml",
        "views/pos_order_upload_view.xml",
        "views/pos_transaction_code_view.xml",
        "views/res_division_file_view.xml",
        "views/res_department_file_view.xml",
        "views/product_items_file_view.xml",
        "views/product_barcode_file_view.xml",
        "views/product_category_file_view.xml",
        "views/product_subcategory_file_view.xml",
        "views/price_change_file_view.xml",
        "views/group_price_change_file_view.xml",
        "views/mix_and_match_combination_file_view.xml",
        "views/mix_and_match_partial_file_view.xml",
        "views/inherit_account_tax_view.xml",
        "views/inherit_uom_view.xml",
        "views/inherit_product_categ_view.xml",
        "views/inherit_pos_payment_method_view.xml",
        "views/inherit_pos_config_view.xml",
        "views/menu_view.xml",
    ],
}
