# Copyright 2020 Tecnativa - Carlos Dauden
# Copyright 2020 Tecnativa - Sergio Teruel
# License AGPL-3.0 or later (https://www.gnu.org/licenses/agpl).
{
    "name": "Agreement Rebate",
    "summary": "Rebate in agreements",
    "version": "16.0.1.0.0",
    "development_status": "Beta",
    "category": "Agreement",
    "website": "https://github.com/OCA/agreement",
    "author": "Tecnativa, Odoo Community Association (OCA)",
    "license": "AGPL-3",
    "application": False,
    "installable": True,
    "depends": ["base", 
                "account", 
                "account_invoice_refund_link", 
                "agreement", 
                "product", 
                "purchase", 
                "point_of_sale",
                "multi_branch_base"],
    "data": [
        "data/agreement_rebate_data.xml",
        "security/agreement_rebate_security.xml",
        "security/ir.model.access.csv",
        "views/agreement_condition_view.xml",
        "views/agreement_view.xml",
        "views/agreement_rebate_settlement_view.xml",
        "views/agreement_rebate_settlement_line_view.xml",
        "views/agreement_type.xml",
        # "views/product_supplierinfo_view.xml",
        "views/product_template_view.xml",
        "views/contract_outright_settlement_view.xml",
        "views/contract_outright_settlement_line_view.xml",
        "views/contract_conces_settlement_view.xml",
        "views/contract_conces_settlement_line_view.xml",
        "views/settings.xml",
        "wizards/invoice_create_views.xml",
        "wizards/contract_invoice_create_view.xml",
        "wizards/settlement_create_views.xml",
        "wizards/contract_settlement_create_view.xml",
        "views/agreement_menu_view.xml",
    ],
}
